--
-- PostgreSQL database dump
--

-- Dumped from database version 11.3
-- Dumped by pg_dump version 11.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: osamagamal
--

COPY public.categories (type) FROM stdin;
Science
Art
Geography
History
Entertainment
Sports
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: osamagamal
--

COPY public.questions (question, answer, difficulty, category) FROM stdin;
Whose autobiography is entitled 'I Know Why the Caged Bird Sings'?	Maya Angelou	2	4
What boxer's original name is Cassius Clay?	Muhammad Ali	1	4
What movie earned Tom Hanks his third straight Oscar nomination, in 1996?	Apollo 13	4	5
What actor did author Anne Rice first denounce, then praise in the role of her beloved Lestat?	Tom Cruise	4	5
What was the title of the 1990 fantasy directed by Tim Burton about a young man with multi-bladed appendages?	Edward Scissorhands	3	5
Which is the only team to play in every soccer World Cup tournament?	Brazil	3	6
Which country won the first ever soccer World Cup in 1930?	Uruguay	4	6
Who invented Peanut Butter?	George Washington Carver	2	4
What is the largest lake in Africa?	Lake Victoria	2	3
In which royal palace would you find the Hall of Mirrors?	The Palace of Versailles	3	3
The Taj Mahal is located in which Indian city?	Agra	2	3
Which Dutch graphic artist–initials M C was a creator of optical illusions?	Escher	1	2
La Giaconda is better known as what?	Mona Lisa	3	2
How many paintings did Van Gogh sell in his lifetime?	One	4	2
Which American artist was a pioneer of Abstract Expressionism, and a leading exponent of action painting?	Jackson Pollock	2	2
What is the heaviest organ in the human body?	The Liver	4	1
Who discovered penicillin?	Alexander Fleming	3	1
Hematology is a branch of medicine involving the study of what?	Blood	4	1
Which dung beetle was worshipped by the ancient Egyptians?	Scarab	4	4
\.


--
-- PostgreSQL database dump complete
--

